language: node_js

node_js:
- '8.4.0'

addons:
  chrome: stable

install:
- npm install

script:
- npm run pretest
- npm run test:custom-login
- npm run test:resource-server

before_install:
  - "npm install -g npm@5.6.0"
